### ISSUE TITLE
Skipped query-string version in check function in "Development" mode 

### ISSUE THREAD

**Issue by bipboy** [pbeshai/serialize-query-params#42]
Skipped query-string 7 version check function in the in "Development" mode in the index.ts file, the regular expression in it only checks to version 6. 

```
const validQueryStringInstalled =
    /^5.1.[1-9][0-9]*/.test(queryStringVersion) ||
    /^6\./.test(queryStringVersion);
  if (!validQueryStringInstalled) {
    throw new Error(
      `serialize-query-params requires query-string ^5.1.1 || ^6, ` +
        `but ${queryStringVersion} is installed. Note: you may also ` +
        `see this message if you're using use-query-params.`
    );
  }
}
```

Error:

```

/home/bipboy/project/test/common/temp/node_modules/.pnpm/serialize-query-params@1.3.2_query-string@7.0.0/node_modules/serialize-query-params/lib/index.js:63
        throw new Error("serialize-query-params requires query-string ^5.1.1 || ^6, " +
        ^

Error: serialize-query-params requires query-string ^5.1.1 || ^6, but 7.0.0 is installed. Note: you may also see this message if you're using use-query-params.
    at Object.<anonymous> (/home/bipboy/project/test/common/temp/node_modules/.pnpm/serialize-query-params@1.3.2_query-string@7.0.0/node_modules/serialize-query-params/lib/index.js:63:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/bipboy/project/test/common/temp/node_modules/.pnpm/use-query-params@1.2.1_fbb1568849e39ef343f2f6b5a928879a/node_modules/use-query-params/lib/index.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

```

**Comment by pbeshai** [comment]
Fixed in #43 v1.3.3
